---
repos:
  # ---------------- formatters ----------------
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length=100"]
        files: ^(agents|core|services|tests|agent\.py)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        language_version: python3.11
        files: ^(agents|core|services|tests|agent\.py)$
      - id: ruff-format
        language_version: python3.11
        files: ^(agents|core|services|tests|agent\.py)$

  # ---------------- quality / safety ----------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
