# docker-compose.yml - MonaQueHabla v1.9.0
# IP del host: 192.168.1.84
# Generado: 2025-06-12 15:49:36

services:
  token-server:
    build:
      context: .
      dockerfile: Dockerfile.local
      target: development
    container_name: monaquehabla-token-server
    ports:
      - "8000:8000"
    env_file:
      - .env
      - .env.local
    environment:
      - PYTHONUNBUFFERED=1
      - LIVEKIT_URL=ws://192.168.1.84:7880
      - PORT=8000
    volumes:
      - ./services:/app/services
      - ./frontend:/app/frontend:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: python services/token_server.py

  voice-agent:
    build:
      context: .
      dockerfile: Dockerfile.local
      target: development
    container_name: monaquehabla-voice-agent
    ports:
      - "8081:8081"
    env_file:
      - .env
      - .env.local
    environment:
      - PYTHONUNBUFFERED=1
      - LIVEKIT_URL=ws://192.168.1.84:7880
      - PORT=8081
    volumes:
      - ./agents:/app/agents
      - ./core:/app/core
      - ./services:/app/services
      - ./personas:/app/personas:ro
    restart: unless-stopped
    depends_on:
      token-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: python agent.py start

  frontend:
    image: nginx:alpine
    container_name: monaquehabla-frontend
    ports:
      - "5000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:rw
    restart: unless-stopped

networks:
  default:
    name: monaquehabla-network
